name: Test

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.1
            symfony-version: 5.4.*
            composer-args: prefer-lowest
            node-version: 12
          - php-version: 8.1
            symfony-version: 6.4.*
            composer-args: ""
            node-version: 12
          - php-version: 8.2
            symfony-version: 5.4.*
            composer-args: ""
            node-version: 12
          - php-version: 8.2
            symfony-version: 6.4.*
            composer-args: ""
            node-version: 12

    name: PHP ${{ matrix.php-version }} Test with Symfony ${{ matrix.symfony-version }} and ${{ matrix.composer-args }}
    steps:
      # —— Setup Github actions 🐙 —————————————————————————————————————————————
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug #optional

      # https://github.com/marketplace/actions/setup-php-action#problem-matchers
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      # https://github.com/marketplace/actions/setup-php-action#problem-matchers
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      # —— Composer 🧙‍️ —————————————————————————————————————————————————————————
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ matrix.symfony-version }}--${{ matrix.stability }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ matrix.symfony-version }}--${{ matrix.stability }}-

      - name: Install NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Validate Composer.json
        run: composer validate

      - name: Install PHP dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader --${{ matrix.composer-args }}
      ## —— Test ✅ ———————————————————————————————————————————————————————————
      - name: Run Tests
        run: php vendor/bin/codecept run
